version: "3.9"  
services:

  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"      
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml   
    links:
     - "csvserver"

  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    environment:
    - CSVSERVER_BORDER=Orange
    volumes:
      - ./inputFile:/csvserver/inputdata     